name: WhatAmIDoing
options:
  bundleIdPrefix: com.katiawheeler
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  WhatAmIDoing:
    type: application
    platform: macOS
    sources:
      - WhatAmIDoingApp.swift
      - DrawerWindow.swift
      - Models
      - Views
      - ViewModels
      - Utilities
      - path: Resources/Assets.xcassets
      - path: Resources/Fonts
        type: folder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.katiawheeler.WhatAmIDoing
        PRODUCT_NAME: "What Am I Doing?"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ENABLE_HARDENED_RUNTIME: YES
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
    info:
      path: Info.plist
      properties:
        CFBundleIconFile: AppIcon
